---
- name: Install Docker
  hosts: dockernodes
  remote_user: nova
  become: yes
  become_method: sudo
  vars:
    timezone: "America/Chicago"                  # Timezone to set on all nodes 
    docker_user: nova
    # Docker proxy support
    setup_proxy: false                           # Set to true to configure proxy
    proxy_server: "proxy.example.com:8080"       # Proxy server address and port
    docker_proxy_exclude: "localhost,127.0.0.1"  # Adresses to exclude from proxy
  roles:
    - docker-bootstrap
