---
- name: Mount NFS
  hosts: k8sworkers
  remote_user: nova
  become: yes
  become_method: sudo
  #gather_facts: no
  vars:
    mount_src: "10.1.20.91:/volume2/media"
    mount_path: "/mnt/media"
    mount_opts: "vers=4.1,hard,nolock,tcp,intr"
    mount_mode: "0775"
    mount_owner: "nova"
    mount_group: "nova"
  roles:
    - mount-nfs
